### ISSUE TITLE
Bug from growing tree

### ISSUE THREAD

**Issue by VincoNafta** [BentoBoxWorld/DimensionalTrees#9]
Hi. I found one bug, if player place a sapling and use bonemeal in nether the tree growing normally. If I try for Oak Wood, it is working. This growing normally works only on OakWood. Please fix it  
look on this picture
![image](https://user-images.githubusercontent.com/62835475/79136661-a76f6400-7db1-11ea-8fd9-24c40b66c6e9.png)

**Comment by Awakened-Redstone** [comment]
on settings you can set the types of trees that transform on the dimensions
